version: 2
updates:
  # Python dependencies located in /server
  - package-ecosystem: "pip"
    directory: "/server"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
    assignees:
      - "Auctic-Flipper"

  # Keep GitHub Actions up to date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
