-- ============================================================
-- PARKING GARAGE TRACKING SYSTEM
-- 1 Garage, 2 Sections (Faculty: 97, Student: 299)
-- 3 Cameras: A (Faculty Entry), B (Faculty→Student Transfer), C (Student Entry)
-- ============================================================

-- ------------------------------------------------------------
-- 0) Extensions & Enums
-- ------------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS pgcrypto;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'direction') THEN
    CREATE TYPE direction AS ENUM ('in','out');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'section_event_kind') THEN
    CREATE TYPE section_event_kind AS ENUM ('in','out','transfer');
  END IF;
END$$;

-- ------------------------------------------------------------
-- 1) Reference Tables
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS garages (
  id   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS cameras (
  id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  garage_id  uuid NOT NULL REFERENCES garages(id) ON DELETE CASCADE,
  name       text NOT NULL,
  code       text NOT NULL CHECK (code IN ('A','B','C')),
  description text,
  UNIQUE (garage_id, code)
);

-- Sections: Faculty (97 capacity) and Student (299 capacity)
CREATE TABLE IF NOT EXISTS sections (
  id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  garage_id  uuid NOT NULL REFERENCES garages(id) ON DELETE CASCADE,
  name       text NOT NULL,
  code       text NOT NULL CHECK (code IN ('Faculty','Student')),
  capacity   integer NOT NULL CHECK (capacity > 0),
  UNIQUE (garage_id, code)
);

-- ------------------------------------------------------------
-- 2) Seed Default Data
-- ------------------------------------------------------------
INSERT INTO garages(name) VALUES ('Main Garage')
ON CONFLICT (name) DO NOTHING;

WITH g AS (
  SELECT id FROM garages WHERE name='Main Garage'
)
INSERT INTO cameras(garage_id, name, code, description)
SELECT g.id, v.n, v.c, v.d
FROM g, (VALUES 
  ('Camera A', 'A', 'Tracks cars entering Faculty section from outside'),
  ('Camera B', 'B', 'Tracks cars leaving Faculty and entering Student section'),
  ('Camera C', 'C', 'Tracks cars entering Student section from outside')
) AS v(n, c, d)
ON CONFLICT (garage_id, code) DO NOTHING;

WITH g AS (SELECT id FROM garages WHERE name='Main Garage')
INSERT INTO sections(garage_id, name, code, capacity)
VALUES
  ((SELECT id FROM g), 'Faculty Section', 'Faculty', 97),
  ((SELECT id FROM g), 'Student Section', 'Student', 299)
ON CONFLICT (garage_id, code) DO NOTHING;

-- ------------------------------------------------------------
-- 3) Event Tables
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS camera_events (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  garage_id    uuid NOT NULL REFERENCES garages(id) ON DELETE CASCADE,
  camera_id    uuid NOT NULL REFERENCES cameras(id) ON DELETE CASCADE,
  dir          direction NOT NULL,
  confidence   numeric(4,3),
  frame_ts     timestamptz NOT NULL,
  received_at  timestamptz NOT NULL DEFAULT now(),
  dedupe_key   text,
  meta         jsonb NOT NULL DEFAULT '{}'::jsonb
);

-- Dedupe: one event per camera per direction per timestamp per dedupe_key
CREATE UNIQUE INDEX IF NOT EXISTS uq_camera_events_dedupe
ON camera_events (garage_id, camera_id, dir, frame_ts, COALESCE(dedupe_key,'__ndk__'));

CREATE INDEX IF NOT EXISTS ix_camera_events_garage_ts ON camera_events(garage_id, frame_ts DESC);
CREATE INDEX IF NOT EXISTS ix_camera_events_camera_ts ON camera_events(camera_id, frame_ts DESC);

CREATE TABLE IF NOT EXISTS section_events (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  garage_id    uuid NOT NULL REFERENCES garages(id) ON DELETE CASCADE,
  kind         section_event_kind NOT NULL,
  from_section uuid REFERENCES sections(id) ON DELETE SET NULL,
  to_section   uuid REFERENCES sections(id) ON DELETE SET NULL,
  camera_id    uuid REFERENCES cameras(id) ON DELETE SET NULL,
  frame_ts     timestamptz NOT NULL,
  dedupe_key   text,
  meta         jsonb NOT NULL DEFAULT '{}'::jsonb,
  CHECK (
    (kind='in'  AND from_section IS NULL AND to_section IS NOT NULL) OR
    (kind='out' AND from_section IS NOT NULL AND to_section IS NULL) OR
    (kind='transfer' AND from_section IS NOT NULL AND to_section IS NOT NULL AND from_section <> to_section)
  )
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_section_events_dedupe
ON section_events (
  garage_id, 
  kind, 
  COALESCE(from_section,'00000000-0000-0000-0000-000000000000'::uuid), 
  COALESCE(to_section,'00000000-0000-0000-0000-000000000000'::uuid), 
  frame_ts, 
  COALESCE(dedupe_key,'__ndk__')
);

CREATE INDEX IF NOT EXISTS ix_section_events_garage_ts ON section_events(garage_id, frame_ts DESC);

-- ------------------------------------------------------------
-- 4) Live State Management
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS section_state (
  section_id uuid PRIMARY KEY REFERENCES sections(id) ON DELETE CASCADE,
  occupied   integer NOT NULL DEFAULT 0 CHECK (occupied >= 0),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Initialize section_state for all sections
INSERT INTO section_state(section_id)
SELECT s.id
FROM sections s
LEFT JOIN section_state st ON st.section_id = s.id
WHERE st.section_id IS NULL;

-- ------------------------------------------------------------
-- 5) Helper Functions
-- ------------------------------------------------------------

-- Compute deltas from section_events
CREATE OR REPLACE FUNCTION _section_event_deltas(
  p_kind section_event_kind,
  p_from uuid,
  p_to   uuid
) RETURNS TABLE (section_id uuid, delta integer)
LANGUAGE SQL STABLE AS $$
  SELECT p_to   AS section_id, +1 AS delta WHERE p_kind='in'
  UNION ALL
  SELECT p_from AS section_id, -1 AS delta WHERE p_kind='out'
  UNION ALL
  SELECT p_from AS section_id, -1 AS delta WHERE p_kind='transfer'
  UNION ALL
  SELECT p_to   AS section_id, +1 AS delta WHERE p_kind='transfer'
$$;

-- ------------------------------------------------------------
-- 6) Capacity Enforcement Trigger (BEFORE INSERT)
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION trg_section_events_capacity_guard()
RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
  g_id uuid := NEW.garage_id;
  faculty_id uuid;
  student_id uuid;
  occ_faculty int := 0;
  occ_student int := 0;
  d_faculty int := 0;
  d_student int := 0;
  sec record;
BEGIN
  -- Get section IDs
  SELECT id INTO faculty_id FROM sections WHERE garage_id=g_id AND code='Faculty';
  SELECT id INTO student_id FROM sections WHERE garage_id=g_id AND code='Student';

  -- Get current occupancy
  SELECT COALESCE(st.occupied,0) INTO occ_faculty
  FROM section_state st
  WHERE st.section_id = faculty_id;

  SELECT COALESCE(st.occupied,0) INTO occ_student
  FROM section_state st
  WHERE st.section_id = student_id;

  -- Calculate deltas from this event
  FOR sec IN SELECT * FROM _section_event_deltas(NEW.kind, NEW.from_section, NEW.to_section)
  LOOP
    IF sec.section_id = faculty_id THEN
      d_faculty := d_faculty + sec.delta;
    ELSIF sec.section_id = student_id THEN
      d_student := d_student + sec.delta;
    END IF;
  END LOOP;

  -- Apply deltas
  occ_faculty := occ_faculty + d_faculty;
  occ_student := occ_student + d_student;

  -- Enforce capacity limits
  IF occ_faculty > 97 THEN
    RAISE EXCEPTION 'Capacity exceeded for Faculty Section (would be % > 97)', occ_faculty
      USING ERRCODE = 'check_violation';
  END IF;

  IF occ_student > 299 THEN
    RAISE EXCEPTION 'Capacity exceeded for Student Section (would be % > 299)', occ_student
      USING ERRCODE = 'check_violation';
  END IF;

  -- Prevent negative occupancy
  IF occ_faculty < 0 THEN
    RAISE EXCEPTION 'Faculty Section occupancy would go negative (%)', occ_faculty
      USING ERRCODE = 'check_violation';
  END IF;

  IF occ_student < 0 THEN
    RAISE EXCEPTION 'Student Section occupancy would go negative (%)', occ_student
      USING ERRCODE = 'check_violation';
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tbi_section_events_capacity_guard ON section_events;
CREATE TRIGGER tbi_section_events_capacity_guard
BEFORE INSERT ON section_events
FOR EACH ROW EXECUTE FUNCTION trg_section_events_capacity_guard();

-- ------------------------------------------------------------
-- 7) Apply Events to State (AFTER INSERT)
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION trg_section_events_apply()
RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
  r record;
BEGIN
  FOR r IN SELECT * FROM _section_event_deltas(NEW.kind, NEW.from_section, NEW.to_section)
  LOOP
    UPDATE section_state
       SET occupied = occupied + r.delta,
           updated_at = now()
     WHERE section_id = r.section_id;
  END LOOP;
  RETURN NULL;
END;
$$;

DROP TRIGGER IF EXISTS tai_section_events_apply ON section_events;
CREATE TRIGGER tai_section_events_apply
AFTER INSERT ON section_events
FOR EACH ROW EXECUTE FUNCTION trg_section_events_apply();

-- ------------------------------------------------------------
-- 8) Views for Monitoring
-- ------------------------------------------------------------

-- Current state per section
CREATE OR REPLACE VIEW vw_section_occupancy AS
SELECT 
  s.garage_id,
  g.name AS garage_name,
  s.id AS section_id,
  s.name AS section_name,
  s.code AS section_code,
  s.capacity,
  COALESCE(st.occupied, 0) AS occupied,
  s.capacity - COALESCE(st.occupied, 0) AS available,
  ROUND(100.0 * COALESCE(st.occupied, 0) / s.capacity, 1) AS occupancy_percent,
  st.updated_at
FROM sections s
JOIN garages g ON g.id = s.garage_id
LEFT JOIN section_state st ON st.section_id = s.id
ORDER BY s.code;

-- Overall garage state
CREATE OR REPLACE VIEW vw_garage_summary AS
SELECT 
  g.id AS garage_id,
  g.name AS garage_name,
  SUM(s.capacity) AS total_capacity,
  SUM(COALESCE(st.occupied, 0)) AS total_occupied,
  SUM(s.capacity) - SUM(COALESCE(st.occupied, 0)) AS total_available,
  ROUND(100.0 * SUM(COALESCE(st.occupied, 0)) / SUM(s.capacity), 1) AS occupancy_percent
FROM garages g
JOIN sections s ON s.garage_id = g.id
LEFT JOIN section_state st ON st.section_id = s.id
GROUP BY g.id, g.name;

-- Recent section events with details
CREATE OR REPLACE VIEW vw_recent_section_events AS
SELECT 
  se.id,
  se.garage_id,
  g.name AS garage_name,
  se.kind,
  sf.name AS from_section_name,
  st.name AS to_section_name,
  c.name AS camera_name,
  se.frame_ts,
  se.received_at,
  se.meta
FROM section_events se
JOIN garages g ON g.id = se.garage_id
LEFT JOIN sections sf ON sf.id = se.from_section
LEFT JOIN sections st ON st.id = se.to_section
LEFT JOIN cameras c ON c.id = se.camera_id
ORDER BY se.frame_ts DESC
LIMIT 100;

-- Camera activity summary
CREATE OR REPLACE VIEW vw_camera_activity AS
SELECT 
  c.id AS camera_id,
  c.name AS camera_name,
  c.code AS camera_code,
  c.description,
  COUNT(ce.id) AS total_events,
  COUNT(CASE WHEN ce.dir = 'in' THEN 1 END) AS in_events,
  COUNT(CASE WHEN ce.dir = 'out' THEN 1 END) AS out_events,
  MAX(ce.frame_ts) AS last_event_time
FROM cameras c
LEFT JOIN camera_events ce ON ce.camera_id = c.id
GROUP BY c.id, c.name, c.code, c.description
ORDER BY c.code;

-- ------------------------------------------------------------
-- 9) Helper Function: Process Camera Event
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION process_camera_event(
  p_camera_code text,
  p_direction direction,
  p_frame_ts timestamptz,
  p_dedupe_key text DEFAULT NULL,
  p_confidence numeric DEFAULT NULL,
  p_meta jsonb DEFAULT '{}'::jsonb
) RETURNS jsonb
LANGUAGE plpgsql AS $$
DECLARE
  v_garage_id uuid;
  v_camera_id uuid;
  v_faculty_id uuid;
  v_student_id uuid;
  v_camera_event_id bigint;
  v_section_event_id bigint;
  v_result jsonb;
BEGIN
  -- Get garage and camera
  SELECT g.id, c.id INTO v_garage_id, v_camera_id
  FROM garages g
  JOIN cameras c ON c.garage_id = g.id
  WHERE g.name = 'Main Garage' AND c.code = p_camera_code;

  IF v_camera_id IS NULL THEN
    RAISE EXCEPTION 'Camera % not found', p_camera_code;
  END IF;

  -- Get section IDs
  SELECT id INTO v_faculty_id FROM sections WHERE garage_id = v_garage_id AND code = 'Faculty';
  SELECT id INTO v_student_id FROM sections WHERE garage_id = v_garage_id AND code = 'Student';

  -- Insert camera event
  INSERT INTO camera_events (garage_id, camera_id, dir, confidence, frame_ts, dedupe_key, meta)
  VALUES (v_garage_id, v_camera_id, p_direction, p_confidence, p_frame_ts, p_dedupe_key, p_meta)
  RETURNING id INTO v_camera_event_id;

  -- Process based on camera and direction
  IF p_camera_code = 'A' AND p_direction = 'in' THEN
    -- Camera A IN: Car entering Faculty section
    INSERT INTO section_events (garage_id, kind, to_section, camera_id, frame_ts, dedupe_key, meta)
    VALUES (v_garage_id, 'in', v_faculty_id, v_camera_id, p_frame_ts, p_dedupe_key, p_meta)
    RETURNING id INTO v_section_event_id;

  ELSIF p_camera_code = 'B' AND p_direction = 'in' THEN
    -- Camera B IN: Car leaving Faculty, entering Student (transfer)
    INSERT INTO section_events (garage_id, kind, from_section, to_section, camera_id, frame_ts, dedupe_key, meta)
    VALUES (v_garage_id, 'transfer', v_faculty_id, v_student_id, v_camera_id, p_frame_ts, p_dedupe_key, p_meta)
    RETURNING id INTO v_section_event_id;

  ELSIF p_camera_code = 'C' AND p_direction = 'in' THEN
    -- Camera C IN: Car entering Student section from outside
    INSERT INTO section_events (garage_id, kind, to_section, camera_id, frame_ts, dedupe_key, meta)
    VALUES (v_garage_id, 'in', v_student_id, v_camera_id, p_frame_ts, p_dedupe_key, p_meta)
    RETURNING id INTO v_section_event_id;

  ELSE
    -- Unexpected camera/direction combination
    v_section_event_id := NULL;
  END IF;

  -- Build result
  v_result := jsonb_build_object(
    'success', true,
    'camera_event_id', v_camera_event_id,
    'section_event_id', v_section_event_id,
    'camera_code', p_camera_code,
    'direction', p_direction,
    'timestamp', p_frame_ts
  );

  RETURN v_result;
END;
$$;
